services:
  # Updater service only - runs as root with Docker socket access (isolated)
  updater:
    build: ./updater
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # if using custom login data to e.g. your private registry, mount the docker config as well
      - /root/.docker:/root/.docker:ro
      # if using docker compose files, mount this directory as well
      - /tmp/docker-autoupdater-test:/tmp/docker-autoupdater-test:ro
    environment:
      CHECK_INTERVAL: 5
      UPDATE_INTERVAL: 900  # 15 minutes
      # No trigger file when running standalone - only scheduled updates
    restart: unless-stopped
