services:
  # Updater service only - runs as root with Docker socket access (isolated)
  updater:
    build: ./updater
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CHECK_INTERVAL: 5
      UPDATE_INTERVAL: 900  # 15 minutes
      # No trigger file when running standalone - only scheduled updates
    restart: unless-stopped
